databases:
  - name: nestedinfo_db
    databaseName: nestedinfo_db
    user: nestedinfo_user

services:
  - type: web
    name: nestedinfo-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nestedinfo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.14.2
