databases:
  - name: nestedinfo_db
    databaseName: nestedinfo_db
    user: nestedinfo_user

services:
  - type: web
    name: nestedinfo-backend
    runtime: python
    rootDir: backend
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nestedinfo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
